### ISSUE TITLE
Dependency issues while running prepare_data.py

### ISSUE THREAD

**Issue by srikhetramohanty** [OpenLLM-France/Claire#6]
Hi, I was trying to get this repository to run with the existing data. While running the prepare_data.py step I am getting this import error `ImportError: cannot import name '_materialize_meta_tensors' from 'lightning.fabric.utilities.init'` though the correct version of lightning is installed. 

Note - I also resolved a lot of dependencies including frquent changes in path name of lit-gpt/lit_gpt to litgpt. 

Please help me find a resolution.

**Comment by Jeronymous** [comment]
Sorry @srikhetramohanty we all missed the opening of your issue.

Indeed it can be tricky to install things with all those neural network librairies that keep evolving quite fast.

But I am surprised, because we were careful to describe how we could get an environment working.
Are you sure you followed all the setup instruction in the README, in particular :
```
# clone with reurse submodules, it is important to use the custom version of litgpt
git clone --recurse-submodules git@github.com:OpenLLM-France/Lit-Claire.git

# also need particular version of pytorch-lightning
pip install pytorch-lightning==2.1.2
pip install torch==2.2.0.dev20231127+cu121 -f https://download.pytorch.org/whl/nightly/torch/
```

If you keep having this error, please give the full stack of errors (which package is trying to import an unexisting function in lightning?) in case it rings a bell.

(Closing the issue because it's old, don't hesistate to re-open if such problem persists)
